"""行业预设参数库。

4 个行业 × 3 个模型 = 12 个预设参数包。
用户可在前端一键加载，避免从零开始设置 28-32 个参数。

预设值基于行业经验和公开市场数据，仅供参考。
"""
from typing import Dict, Any, List


PRESETS: Dict[str, Dict[str, Any]] = {
    # ==================== 科技 / SaaS ====================
    "tech_saas": {
        "name": "科技/SaaS",
        "name_en": "Tech / SaaS",
        "icon": "💻",
        "description": "高增长(20-30%)、高毛利(70%+)、轻资产、高研发投入、高估值倍数。代表: 软件公司",
        "params": {
            "three_statement": {
                "company_name": "TechCo 科技公司",
                "projection_years": 5,
                "revenue_y0": 200.0,
                "rev_growth_y1": 0.30,
                "rev_growth_y2": 0.25,
                "rev_growth_y3": 0.20,
                "rev_growth_y4": 0.15,
                "rev_growth_y5": 0.12,
                "cogs_pct": 0.30,
                "sga_pct": 0.25,
                "rd_pct": 0.15,
                "da_pct": 0.03,
                "interest_rate": 0.04,
                "tax_rate": 0.20,
                "dividend_pct": 0.0,
                "capex_pct": 0.03,
                "dso": 45.0,
                "dio": 15.0,
                "dpo": 30.0,
                "accrued_days": 25.0,
                "beg_cash": 80.0,
                "beg_ar": 25.0,
                "beg_inventory": 8.0,
                "beg_ppe": 30.0,
                "beg_ap": 15.0,
                "beg_accrued": 20.0,
                "beg_debt": 20.0,
                "common_stock": 100.0,
                "beg_retn_earn": 50.0,
                "new_debt_issuance": 0.0,
            },
            "dcf": {
                "company_name": "TechCo 科技公司",
                "projection_years": 5,
                "revenue_y0": 200.0,
                "rev_growth_y1": 0.30,
                "rev_growth_y2": 0.25,
                "rev_growth_y3": 0.20,
                "rev_growth_y4": 0.15,
                "rev_growth_y5": 0.12,
                "ebitda_margin_y1": 0.35,
                "ebitda_margin_y2": 0.38,
                "ebitda_margin_y3": 0.40,
                "ebitda_margin_y4": 0.42,
                "ebitda_margin_y5": 0.45,
                "da_pct": 0.03,
                "capex_pct": 0.03,
                "nwc_pct": 0.05,
                "tax_rate": 0.20,
                "risk_free_rate": 0.04,
                "equity_risk_premium": 0.05,
                "beta": 1.30,
                "pre_tax_cost_of_debt": 0.05,
                "debt_weight": 0.10,
                "terminal_growth": 0.03,
                "exit_multiple": 18.0,
                "tv_method": "gordon",
                "net_debt": 10.0,
                "cash": 80.0,
                "minority_interest": 0.0,
                "preferred_stock": 0.0,
                "stock_based_comp": 8.0,
                "pension_deficit": 0.0,
                "shares_outstanding": 50.0,
                "current_price": 25.0,
                "valuation_timing": "mid",
            },
            "lbo": {
                "company_name": "TechCo 科技公司",
                "ltm_revenue": 200.0,
                "ltm_ebitda": 70.0,
                "entry_ev_ebitda": 12.0,
                "existing_net_debt": 20.0,
                "existing_cash": 80.0,
                "transaction_fees": 8.0,
                "financing_fees": 12.0,
                "sponsor_equity": 300.0,
                "revolver_capacity": 50.0,
                "term_loan_a": 150.0,
                "term_loan_b": 200.0,
                "senior_notes": 100.0,
                "subordinated_debt": 50.0,
                "revolver_rate": 0.045,
                "tla_rate": 0.045,
                "tlb_rate": 0.055,
                "senior_notes_rate": 0.07,
                "sub_rate": 0.10,
                "tla_mandatory_amort": 0.05,
                "tlb_mandatory_amort": 0.02,
                "cash_sweep_pct": 0.50,
                "min_cash_balance": 15.0,
                "rev_growth_y1": 0.15,
                "rev_growth_y2": 0.12,
                "rev_growth_y3": 0.10,
                "rev_growth_y4": 0.08,
                "rev_growth_y5": 0.06,
                "ebitda_margin": 0.35,
                "da_pct": 0.03,
                "capex_pct": 0.03,
                "nwc_pct": 0.05,
                "tax_rate": 0.20,
                "exit_ev_ebitda": 12.0,
                "exit_year": 5,
                "cash_interest_rate": 0.02,
            },
        },
    },

    # ==================== 零售 / 消费品 ====================
    "retail": {
        "name": "零售/消费品",
        "name_en": "Retail / Consumer",
        "icon": "🛒",
        "description": "中低增长(5-8%)、中等毛利(35-40%净利)、高营运资本需求、重渠道。代表: 实体零售、快消",
        "params": {
            "three_statement": {
                "company_name": "RetailCo 零售公司",
                "projection_years": 5,
                "revenue_y0": 500.0,
                "rev_growth_y1": 0.08,
                "rev_growth_y2": 0.07,
                "rev_growth_y3": 0.06,
                "rev_growth_y4": 0.05,
                "rev_growth_y5": 0.04,
                "cogs_pct": 0.65,
                "sga_pct": 0.22,
                "rd_pct": 0.01,
                "da_pct": 0.03,
                "interest_rate": 0.05,
                "tax_rate": 0.25,
                "dividend_pct": 0.40,
                "capex_pct": 0.04,
                "dso": 7.0,
                "dio": 60.0,
                "dpo": 45.0,
                "accrued_days": 15.0,
                "beg_cash": 50.0,
                "beg_ar": 10.0,
                "beg_inventory": 85.0,
                "beg_ppe": 200.0,
                "beg_ap": 40.0,
                "beg_accrued": 25.0,
                "beg_debt": 100.0,
                "common_stock": 150.0,
                "beg_retn_earn": 120.0,
                "new_debt_issuance": 0.0,
            },
            "dcf": {
                "company_name": "RetailCo 零售公司",
                "projection_years": 5,
                "revenue_y0": 500.0,
                "rev_growth_y1": 0.08,
                "rev_growth_y2": 0.07,
                "rev_growth_y3": 0.06,
                "rev_growth_y4": 0.05,
                "rev_growth_y5": 0.04,
                "ebitda_margin_y1": 0.10,
                "ebitda_margin_y2": 0.10,
                "ebitda_margin_y3": 0.11,
                "ebitda_margin_y4": 0.11,
                "ebitda_margin_y5": 0.12,
                "da_pct": 0.03,
                "capex_pct": 0.04,
                "nwc_pct": 0.08,
                "tax_rate": 0.25,
                "risk_free_rate": 0.04,
                "equity_risk_premium": 0.05,
                "beta": 0.90,
                "pre_tax_cost_of_debt": 0.05,
                "debt_weight": 0.30,
                "terminal_growth": 0.02,
                "exit_multiple": 8.0,
                "tv_method": "exit",
                "net_debt": 100.0,
                "cash": 50.0,
                "minority_interest": 0.0,
                "preferred_stock": 0.0,
                "stock_based_comp": 2.0,
                "pension_deficit": 0.0,
                "shares_outstanding": 80.0,
                "current_price": 12.0,
                "valuation_timing": "mid",
            },
            "lbo": {
                "company_name": "RetailCo 零售公司",
                "ltm_revenue": 500.0,
                "ltm_ebitda": 50.0,
                "entry_ev_ebitda": 8.0,
                "existing_net_debt": 100.0,
                "existing_cash": 50.0,
                "transaction_fees": 15.0,
                "financing_fees": 20.0,
                "sponsor_equity": 150.0,
                "revolver_capacity": 60.0,
                "term_loan_a": 120.0,
                "term_loan_b": 150.0,
                "senior_notes": 80.0,
                "subordinated_debt": 30.0,
                "revolver_rate": 0.04,
                "tla_rate": 0.04,
                "tlb_rate": 0.05,
                "senior_notes_rate": 0.07,
                "sub_rate": 0.10,
                "tla_mandatory_amort": 0.05,
                "tlb_mandatory_amort": 0.02,
                "cash_sweep_pct": 0.50,
                "min_cash_balance": 10.0,
                "rev_growth_y1": 0.06,
                "rev_growth_y2": 0.05,
                "rev_growth_y3": 0.04,
                "rev_growth_y4": 0.04,
                "rev_growth_y5": 0.03,
                "ebitda_margin": 0.10,
                "da_pct": 0.03,
                "capex_pct": 0.04,
                "nwc_pct": 0.08,
                "tax_rate": 0.25,
                "exit_ev_ebitda": 9.0,
                "exit_year": 5,
                "cash_interest_rate": 0.02,
            },
        },
    },

    # ==================== 制造业 ====================
    "manufacturing": {
        "name": "制造业",
        "name_en": "Manufacturing",
        "icon": "🏭",
        "description": "低增长(3-5%)、低毛利(20-25%净利)、高CapEx、重资产、长营运资本周期。代表: 工业制造",
        "params": {
            "three_statement": {
                "company_name": "ManufCo 制造公司",
                "projection_years": 5,
                "revenue_y0": 300.0,
                "rev_growth_y1": 0.06,
                "rev_growth_y2": 0.05,
                "rev_growth_y3": 0.04,
                "rev_growth_y4": 0.04,
                "rev_growth_y5": 0.03,
                "cogs_pct": 0.70,
                "sga_pct": 0.12,
                "rd_pct": 0.04,
                "da_pct": 0.08,
                "interest_rate": 0.055,
                "tax_rate": 0.25,
                "dividend_pct": 0.30,
                "capex_pct": 0.12,
                "dso": 55.0,
                "dio": 90.0,
                "dpo": 40.0,
                "accrued_days": 20.0,
                "beg_cash": 30.0,
                "beg_ar": 45.0,
                "beg_inventory": 74.0,
                "beg_ppe": 250.0,
                "beg_ap": 25.0,
                "beg_accrued": 18.0,
                "beg_debt": 120.0,
                "common_stock": 100.0,
                "beg_retn_earn": 180.0,
                "new_debt_issuance": 0.0,
            },
            "dcf": {
                "company_name": "ManufCo 制造公司",
                "projection_years": 5,
                "revenue_y0": 300.0,
                "rev_growth_y1": 0.06,
                "rev_growth_y2": 0.05,
                "rev_growth_y3": 0.04,
                "rev_growth_y4": 0.04,
                "rev_growth_y5": 0.03,
                "ebitda_margin_y1": 0.18,
                "ebitda_margin_y2": 0.18,
                "ebitda_margin_y3": 0.19,
                "ebitda_margin_y4": 0.19,
                "ebitda_margin_y5": 0.20,
                "da_pct": 0.08,
                "capex_pct": 0.12,
                "nwc_pct": 0.10,
                "tax_rate": 0.25,
                "risk_free_rate": 0.04,
                "equity_risk_premium": 0.05,
                "beta": 1.10,
                "pre_tax_cost_of_debt": 0.055,
                "debt_weight": 0.35,
                "terminal_growth": 0.02,
                "exit_multiple": 7.0,
                "tv_method": "gordon",
                "net_debt": 120.0,
                "cash": 30.0,
                "minority_interest": 0.0,
                "preferred_stock": 0.0,
                "stock_based_comp": 3.0,
                "pension_deficit": 5.0,
                "shares_outstanding": 60.0,
                "current_price": 15.0,
                "valuation_timing": "end",
            },
            "lbo": {
                "company_name": "ManufCo 制造公司",
                "ltm_revenue": 300.0,
                "ltm_ebitda": 54.0,
                "entry_ev_ebitda": 7.0,
                "existing_net_debt": 120.0,
                "existing_cash": 30.0,
                "transaction_fees": 12.0,
                "financing_fees": 18.0,
                "sponsor_equity": 150.0,
                "revolver_capacity": 70.0,
                "term_loan_a": 100.0,
                "term_loan_b": 120.0,
                "senior_notes": 60.0,
                "subordinated_debt": 20.0,
                "revolver_rate": 0.045,
                "tla_rate": 0.045,
                "tlb_rate": 0.055,
                "senior_notes_rate": 0.075,
                "sub_rate": 0.11,
                "tla_mandatory_amort": 0.05,
                "tlb_mandatory_amort": 0.02,
                "cash_sweep_pct": 0.50,
                "min_cash_balance": 12.0,
                "rev_growth_y1": 0.05,
                "rev_growth_y2": 0.04,
                "rev_growth_y3": 0.04,
                "rev_growth_y4": 0.03,
                "rev_growth_y5": 0.03,
                "ebitda_margin": 0.18,
                "da_pct": 0.08,
                "capex_pct": 0.12,
                "nwc_pct": 0.10,
                "tax_rate": 0.25,
                "exit_ev_ebitda": 8.0,
                "exit_year": 5,
                "cash_interest_rate": 0.02,
            },
        },
    },

    # ==================== 金融 / 银行 ====================
    "financial_services": {
        "name": "金融/银行",
        "name_en": "Financial Services",
        "icon": "🏛️",
        "description": "特殊指标(净息差、拨备率)。注意: 当前三模型非银行业最佳适配，参数仅作参考映射（净息差→interest_rate, 拨备→rd_pct）",
        "params": {
            "three_statement": {
                "company_name": "FinCo 金融公司",
                "projection_years": 5,
                "revenue_y0": 150.0,
                "rev_growth_y1": 0.08,
                "rev_growth_y2": 0.07,
                "rev_growth_y3": 0.06,
                "rev_growth_y4": 0.05,
                "rev_growth_y5": 0.05,
                "cogs_pct": 0.20,
                "sga_pct": 0.30,
                "rd_pct": 0.08,
                "da_pct": 0.02,
                "interest_rate": 0.03,
                "tax_rate": 0.25,
                "dividend_pct": 0.35,
                "capex_pct": 0.02,
                "dso": 30.0,
                "dio": 5.0,
                "dpo": 20.0,
                "accrued_days": 30.0,
                "beg_cash": 100.0,
                "beg_ar": 12.0,
                "beg_inventory": 2.0,
                "beg_ppe": 40.0,
                "beg_ap": 10.0,
                "beg_accrued": 25.0,
                "beg_debt": 200.0,
                "common_stock": 120.0,
                "beg_retn_earn": 80.0,
                "new_debt_issuance": 0.0,
            },
            "dcf": {
                "company_name": "FinCo 金融公司",
                "projection_years": 5,
                "revenue_y0": 150.0,
                "rev_growth_y1": 0.08,
                "rev_growth_y2": 0.07,
                "rev_growth_y3": 0.06,
                "rev_growth_y4": 0.05,
                "rev_growth_y5": 0.05,
                "ebitda_margin_y1": 0.30,
                "ebitda_margin_y2": 0.30,
                "ebitda_margin_y3": 0.31,
                "ebitda_margin_y4": 0.31,
                "ebitda_margin_y5": 0.32,
                "da_pct": 0.02,
                "capex_pct": 0.02,
                "nwc_pct": 0.03,
                "tax_rate": 0.25,
                "risk_free_rate": 0.04,
                "equity_risk_premium": 0.06,
                "beta": 0.95,
                "pre_tax_cost_of_debt": 0.04,
                "debt_weight": 0.40,
                "terminal_growth": 0.02,
                "exit_multiple": 10.0,
                "tv_method": "gordon",
                "net_debt": 200.0,
                "cash": 100.0,
                "minority_interest": 0.0,
                "preferred_stock": 15.0,
                "stock_based_comp": 3.0,
                "pension_deficit": 0.0,
                "shares_outstanding": 40.0,
                "current_price": 18.0,
                "valuation_timing": "end",
            },
            "lbo": {
                "company_name": "FinCo 金融公司",
                "ltm_revenue": 150.0,
                "ltm_ebitda": 45.0,
                "entry_ev_ebitda": 9.0,
                "existing_net_debt": 200.0,
                "existing_cash": 100.0,
                "transaction_fees": 8.0,
                "financing_fees": 15.0,
                "sponsor_equity": 200.0,
                "revolver_capacity": 40.0,
                "term_loan_a": 80.0,
                "term_loan_b": 100.0,
                "senior_notes": 60.0,
                "subordinated_debt": 20.0,
                "revolver_rate": 0.04,
                "tla_rate": 0.04,
                "tlb_rate": 0.05,
                "senior_notes_rate": 0.065,
                "sub_rate": 0.09,
                "tla_mandatory_amort": 0.05,
                "tlb_mandatory_amort": 0.02,
                "cash_sweep_pct": 0.40,
                "min_cash_balance": 20.0,
                "rev_growth_y1": 0.06,
                "rev_growth_y2": 0.05,
                "rev_growth_y3": 0.05,
                "rev_growth_y4": 0.04,
                "rev_growth_y5": 0.04,
                "ebitda_margin": 0.30,
                "da_pct": 0.02,
                "capex_pct": 0.02,
                "nwc_pct": 0.03,
                "tax_rate": 0.25,
                "exit_ev_ebitda": 9.0,
                "exit_year": 5,
                "cash_interest_rate": 0.02,
            },
        },
    },
}


def list_presets() -> List[Dict[str, str]]:
    """返回预设列表摘要（不含完整参数）。"""
    return [
        {
            "id": pid,
            "name": p["name"],
            "name_en": p["name_en"],
            "icon": p["icon"],
            "description": p["description"],
        }
        for pid, p in PRESETS.items()
    ]


def get_preset(preset_id: str, model_type: str) -> Dict[str, Any]:
    """返回某预设某模型的完整参数。

    抛出 KeyError (预设不存在) 或 ValueError (模型类型在该预设中不存在)。
    """
    if preset_id not in PRESETS:
        raise KeyError(preset_id)
    preset = PRESETS[preset_id]
    if model_type not in preset["params"]:
        raise ValueError(f"Model type {model_type} not in preset {preset_id}")
    return preset["params"][model_type]
